name: Build Kivy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK with Buildozer (Community Image)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app \
            cansik/kivy-buildozer:latest bash -c "
              cd /app &&
              buildozer android debug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
