name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t calorie-counter-builder .

    - name: Build APK in Docker
      run: |
        mkdir -p bin
        docker run --rm -v ${{ github.workspace }}/bin:/home/builder/app/bin calorie-counter-builder

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calorie-counter-apk
        path: bin/*.apk
