name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      env:
        SKIP_JDK_VERSION_CHECK: true

    - name: Accept Android SDK licenses and install build tools
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager --update
        sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools" "tools" "cmdline-tools;latest"
        
    - name: Verify Android SDK installation
      run: |
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_SDK_ROOT/build-tools/ || echo "Build tools directory not found"
        find $ANDROID_SDK_ROOT -name "aidl" -type f || echo "AIDL not found"

    - name: Initialize buildozer
      run: |
        buildozer init || echo "Buildozer spec already exists"
        buildozer android update

    - name: Build APK with Buildozer
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        PATH: "${{ env.ANDROID_SDK_ROOT }}/build-tools/34.0.0:${{ env.ANDROID_SDK_ROOT }}/platform-tools:$PATH"
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: calorie-counter-apk
        path: bin/*.apk
