name: Build Kivy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf automake libtool libtool-bin pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev build-essential gettext texinfo
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.33
          
      - name: Update autotools
        run: |
          sudo apt-get install -y autotools-dev autoconf-archive
          autoreconf --version
          autoconf --version
          
      - name: Install python-for-android with fixes
        run: |
          pip install --upgrade git+https://github.com/kivy/python-for-android.git@master

      - name: Set up Android SDK
        run: |
          export ANDROID_SDK_ROOT=/opt/android-sdk
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown $USER:$USER $ANDROID_SDK_ROOT
          
      - name: Clean Buildozer cache
        run: |
          rm -rf ~/.buildozer
          mkdir -p ~/.buildozer
          
      - name: Clear any existing build artifacts
        run: |
          rm -rf bin/
          rm -rf .buildozer/
          rm -f buildozer.log

      - name: Build APK with Buildozer
        run: |
          export ANDROID_SDK_ROOT=/opt/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export ANDROID_NDK_HOME=$ANDROID_NDK
          export PATH=$PATH:$ANDROID_NDK_HOME
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export CFLAGS="-Wno-error=format-security -Wno-error=incompatible-pointer-types"
          export CPPFLAGS="-Wno-error=format-security -Wno-error=incompatible-pointer-types"
          export LDFLAGS="-Wl,--no-as-needed"
          export AUTORECONF=autoreconf
          export LIBTOOLIZE=libtoolize
          export ACLOCAL_PATH="/usr/share/aclocal"
          buildozer android debug --verbose

      - name: Show build logs on failure
        if: failure()
        run: |
          echo "=== Buildozer log ==="
          if [ -f .buildozer.log ]; then
            tail -100 .buildozer.log
          fi
          echo "=== End of buildozer log ==="

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-output
          path: |
            bin/*.apk
            .buildozer/android/platform/build-*/dists/*/bin/*.apk
            buildozer.log
