name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --install || true
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install system dependencies
        run: |
          brew install autoconf automake libtool pkg-config
          brew install libffi openssl cmake
          
      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cython==0.29.33
          
      - name: Install and setup kivy-ios
        run: |
          pip install kivy-ios
          
      - name: Cache kivy-ios dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.kivy-ios
            ~/.cache/pip
          key: ${{ runner.os }}-kivy-ios-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-kivy-ios-
            
      - name: Build iOS dependencies
        run: |
          # Build required recipes
          kivy-ios build python3 kivy pillow
          
      - name: Create iOS project
        run: |
          # Create the iOS project
          kivy-ios create "Licznik Kalorii" org.dudek.caloriecounter
          
      - name: Copy application files
        run: |
          # Copy our Python app files to the iOS project
          cp main.py "Licznik Kalorii-ios/"
          cp calorie_counter_app.py "Licznik Kalorii-ios/"
          
      - name: Build Xcode project
        run: |
          cd "Licznik Kalorii-ios"
          # Update the project
          kivy-ios update "Licznik Kalorii-ios"
          
      - name: Create IPA for AltStore
        run: |
          cd "Licznik Kalorii-ios"
          # Build for device (unsigned)
          xcodebuild -project "Licznik Kalorii.xcodeproj" -scheme "Licznik Kalorii" -configuration Release -destination "generic/platform=iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
          
          # Create IPA
          mkdir -p Payload
          cp -r build/Release-iphoneos/"Licznik Kalorii.app" Payload/
          zip -r "Licznik_Kalorii.ipa" Payload/
          
      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-project
          path: |
            Licznik Kalorii-ios/Licznik_Kalorii.ipa
            Licznik Kalorii-ios/
            **/*.log
