name: Build iOS with Buildozer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios-buildozer:
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --install || true
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install system dependencies
        run: |
          brew install autoconf automake libtool pkg-config
          brew install libffi openssl cmake

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.33

      - name: Cache buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
          key: ${{ runner.os }}-buildozer-ios-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-ios-

      - name: Build iOS app with Buildozer
        run: |
          buildozer ios debug

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-buildozer-output
          path: |
            bin/
            .buildozer/
            buildozer.log
